### ISSUE TITLE
Maxes out the the CPU

### ISSUE THREAD

**Issue by Dolondro** [silktide/teamster#2]
It maxes out the CPU rather aggressively.

As I'm unhelpful, I won't give any further debug information.

**Comment by downsider** [comment]
Debugging found that this was to do with the (comparatively) high cost of starting up a process against the amount of work the process had to do. 

Most of the worker implementations that encountered this issue use a queue; if the queue had no jobs on it, the commands would quit and be created again in a tight loop. Extending the wait times between finishing a process and starting a new one helped a little, but waiting for a job to appear on the queue is better. Unfortunately, I doubt that is something that Teamster will be able to enforce.
